### inner product 내적

벡터와 벡터를 내적하면 스칼라 값이 나옴  

- $\langle \mathbf{u}, \mathbf{v} \rangle = \mathbf{u} \cdot \mathbf{v} = u_1 v_1 + u_2 v_2 + \cdots + u_n v_n$

- 두 벡터간의 각도와 norm 기반으로 내적을 계산할 수도 있음
    - 유클리드 노름(Euclidean norm)을 사용함. 
    - $\mathbf{u} \cdot \mathbf{v} = \|\mathbf{u}\| \|\mathbf{v}\| \cos(\theta)$

In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

res = np.inner(a, b)
res

32

### norm

- 유클리드 노름 ($L^2$ norm)
    - $\|\mathbf{v}\|_2 = \sqrt{v_1^2 + v_2^2 + \cdots + v_n^2}$
- 맨해튼 노름 ($L^1$ norm)
    - $\|\mathbf{v}\|_1 = |v_1| + |v_2| + \cdots + |v_n|$
- 최대 노름
    - $\|\mathbf{v}\|_\infty = \max(|v_1|, |v_2|, \ldots, |v_n|)$

### 직교 공간과 정규 직교 공간

- 벡터 공간내의 벡터 집합이 서로 간에 `직교(orthogonal)`하면 해당 벡터 공간 = 직교 공간

- 벡터들의 길이가 1이라면 `정규 직교(orthonormal)` 라 표현 함.
    - 정규 직교 하는 벡터를 `정규 직교 벡터` 라 부르며 이 벡터들이 만드는 공간을 `정규 직교 공간(orthonormal space)` 라 함

- 직교 하니까 각 벡터들 아무거나 2개 잡아서 내적 때리면 0이 나오겠죠? $cos{\theta} = 0$ 일테니

#### 벡터의 정규화 (normalization)  

- 벡터 길이가 1이므로 직교 벡터들을 유클리드 노름으로 나누면 직교 벡터를 정규 직표 벡터로 변환할 수 있음  
$
v = \frac{1}{\|u\|} u
$

### 그램 슈미트 과정 (gram-schmidt process)

basis 벡터 ${s_1, s_2, ... s_n}$ 을 직교 기저 벡터로 변환하는 작업.    
즉, 그램 슈미트 과정을 거치면 basis 벡터들이 서로 간에 직교하게 된다.  

#### projection theorm 정사영 정리


- 정사영 벡터 구하기
    - 벡터 u를 v에 정사영 하는 벡터는 다음과 같이 구해진다.  
    $\text{proj}_v(u) = \frac{\mathbf{u} \cdot \mathbf{v}}{\mathbf{v} \cdot \mathbf{v}} \mathbf{v}$


- 정사영 정리  

    벡터 공간 S의 부분 공간 W가 존재할 때, 벡터 공간 S에 속하는 임의의 벡터 a는   
    $a = w_1 + w_2$ 로 표현할 수 있다.  
    $w_1$ 는 부분 공간 W에 속하는 벡터이며 $w_2$는 부분 공간의 직교 공간 $W^\perp$에 속하는 벡터임  

### QR 분해

#### QR 분해가 뭔가

$A = QR$  

A가 n * p 인 행렬일 때 아래로 분리할 수 있다.  
full rank가 아닌 행렬 A 에 대해서도 사용할 수 있음. 대신 그러면 R이 singular고 대각선 원소가 0이 될 수 있습니다

- Q = 정규 직교(orthonomal) 벡터로 이루어진 n * p 행렬   
    - 정규 직교니까 다 길이가 1이고 서로 간 내적이 0, 즉, 직교하는 벡터로 이루어진 행렬
- R = 역행렬이 존재하는 상삼각 행렬 p * p 행렬  
    - non-singular upper triangle matrix


In [14]:
A = np.array([
    [1, 0, 1],
    [0, 1, 1],
    [1, 2, 0],
])

Arank = np.linalg.matrix_rank(A)
print(f"A의 랭크 -> {Arank}")

# Q는 정규 직교로 이뤄진 행렬. 각각이 선형 독립이고 내적하면 0
# R은 non singular 상삼각행렬로 예상 (A가 full rank 라서)
Q, R = np.linalg.qr(A)

print("Q is ")
print(Q)
print("R is ")
print(R)

A의 랭크 -> 3
Q is 
[[-0.70710678  0.57735027 -0.40824829]
 [-0.         -0.57735027 -0.81649658]
 [-0.70710678 -0.57735027  0.40824829]]
R is 
[[-1.41421356 -1.41421356 -0.70710678]
 [ 0.         -1.73205081  0.        ]
 [ 0.          0.         -1.22474487]]


In [13]:

"""
Q는 정규 직교(orthonomal) 행렬이므로 크기가 1이고 각 열벡터가 직교하고 내적이 0일 것이다.
"""
colVec1 = Q[:, 0]
colVec2 = Q[:, 1]
colVec3 = Q[:, 2]

# l2 norm이 1일 것으로 예상
print(f"norm is : {np.linalg.norm(colVec1)}")

# 내적이 0일 것으로 예상
np.allclose(np.inner(colVec1, colVec2), 0)

norm is : 0.9999999999999998


True