In [1]:
import numpy as np

### transpose 전치행렬 $A^T$

$
a_{i, j} = a_{j, i}
$

In [3]:
A = np.array([[1, 5],
              [3, 4],
              [6, 2]])
At = np.transpose(A)

At

array([[1, 3, 6],
       [5, 4, 2]])

### symmetric 대칭 행렬 $A = A^{T}$

$
A = A^{T}
$

- 대각선 기준으로 대칭인 행렬

- 대칭 행렬 $A$는 $ A^{n} $ 꼴은 모두 대칭 행렬이다.
- 모든 행렬 A에 대해서, AA^{T} 는 항상 대칭 행렬 형태다. 
    - A가 정방 행렬일 필요도 없다. 모든 행렬에 해당한다.


In [13]:
A = np.array([
    [1, 0, 2],
    [0, 2, 1],
    [2, 1, 1],
])

At = np.transpose(A)

# 대칭 행렬인가?

np.array_equal(A, At)

True

#### 대칭 행렬 A 에 대해 $A^n$ 또한 대칭행렬이다.

In [14]:
# 대칭 행렬은 곱해서 대칭행렬이다.

temp = A

for i in range(1, 8):
    temp = np.matmul(temp, A)
    tempt = np.transpose(temp)
    print(f"A의 {i + 1} 승은 대칭 행렬인가? {np.array_equal(temp, temp)}")

A의 2 승은 대칭 행렬인가? True
A의 3 승은 대칭 행렬인가? True
A의 4 승은 대칭 행렬인가? True
A의 5 승은 대칭 행렬인가? True
A의 6 승은 대칭 행렬인가? True
A의 7 승은 대칭 행렬인가? True
A의 8 승은 대칭 행렬인가? True


#### $AA^T$ 는 항상 대칭행렬이다

In [15]:
A = np.array([
    [1, 50, 2],
    [9, 23, 1],
    [12, 16, 1],
])

At = np.transpose(A)
res = np.matmul(A, At)

# res가 대칭행렬인지 검증해보자. 검증하려면 transpose 한 것과 같은지 체크해보면 된다.
rest = np.transpose(res)

np.array_equal(res, rest)

True

### Orthogonal Matrix 직교 행렬 $A^T = A^{-1}$

- 직교 한다 = $A^T = A^{-1}$ 이다  
- 따라서 $A^TA = AA^T = I$  이다.


In [47]:
# 각도 정의 (예: 45도)
theta = np.pi / 4

# 직교 행렬 생성
Q = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta), np.cos(theta)]
])

# 행등행렬
I = np.identity(2)

# 행렬 출력
print("직교 행렬 Q:")
print(Q)

# 직교 행렬 검증: Q^T * Q = I
print(np.allclose(np.dot(Q.T, Q), I))

직교 행렬 Q:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
True


### diagonal 대각행렬

- 대각 행렬은 대각선만 원소 있고 나머진 0
- 대각 행렬의 역행렬은 대각 원소들의 역수 $d \rightarrow \frac{1}{d}$
- 대각 행렬의 n승은 대각 원소들의 n승 $d \rightarrow d^{n}$  
- 어떤 행렬에 대각 행렬을 곱한다는 건 해당 행렬의 행이 대각 원소의 배수만큼 커짐을 의미

In [18]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

D = np.diag(A)

print(D) # 대각 원소만 뱉음

print(np.diag(D)) # 다시 넣으면 행렬로 뱉어줌

# 한 번에 행렬만 뱉지 않음. 원한다면 np.diag(np.diag(A)) 같이 해야...

[1 5 9]
[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [25]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

D = np.diag(np.array([1, 3, 4]))

# DA는 A의 행이 각각 1배, 3배, 4배 됨.
# 대각 행렬을 앞에다 곱하면 행이 x배됨
DA = np.matmul(D, A)
print(DA)

print("------")

# AD는 열이 1배, 3배, 4배 됨.
# 대각 행렬을 뒤에다 곱하면 열이 x배됨
AD = np.matmul(A, D)
print(AD)

[[ 1  2  3]
 [12 15 18]
 [28 32 36]]
------
[[ 1  6 12]
 [ 4 15 24]
 [ 7 24 36]]


### identity 단위 행렬

- aka 항등 행렬

In [26]:
I = np.identity(5)

I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
A = np.array([
    [1, 2, 6],
    [31, 72, 56],
    [31, 42, 46],
])

I = np.identity(len(A))

res = np.matmul(A, I)

np.array_equal(A, res)

True

### zero matrix 영행렬

In [32]:
np.zeros((3, 2,)) # 3행 2열의 영행렬

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### triangular matrix 삼각행렬

In [33]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

Aupper = np.triu(A)
print(Aupper)

Alower = np.tril(A)
print(Alower)

[[1 2 3]
 [0 5 6]
 [0 0 9]]
[[1 0 0]
 [4 5 0]
 [7 8 9]]


### toeplitz 토플리츠 행렬

$
A = \begin{bmatrix}
    a & b & c & d & e \\
    f & a & b & c & d \\
    g & f & a & b & c \\
    h & g & f & a & b \\
    i & h & g & f & a 
\end{bmatrix}
$

즉, 
$
T_{i, j} = T_{i + 1, j + 1} = t
$

- 시계열 분석에서 자주 쓰임

In [37]:
from scipy.linalg import toeplitz

A = toeplitz(
    [1, 0, -2, 5], # 하삼각 c
    [1, 3, 6, 9], # 상삼각 r (if c[0] is real, the result is a Hermitian matrix. r[0] is ignored)
)

A

array([[ 1,  3,  6,  9],
       [ 0,  1,  3,  6],
       [-2,  0,  1,  3],
       [ 5, -2,  0,  1]])

### bidiagonal 이중 대각 행렬


upper bidiagonal, lower bidiagonal이 존재함.
- Upper bidiagonal 행렬은 주대각선과 그 바로 위의 부대각선을 제외하고 모든 요소가 0인 행렬입니다.  
$
A = \begin{bmatrix}
    1 & 3 & 0 & 0 \\
    0 & 2 & 2 & 0 \\
    0 & 0 & 3 & 5 \\
    0 & 0 & 0 & 4
\end{bmatrix}
$


- Lower bidiagonal 행렬은 주대각선과 그 바로 아래의 부대각선을 제외하고 모든 요소가 0인 행렬입니다.  
$
B = \begin{bmatrix}
    1 & 0 & 0 & 0 \\
    2 & 2 & 0 & 0 \\
    0 & 1 & 3 & 0 \\
    0 & 0 & 1 & 4
\end{bmatrix}
$

In [42]:
A = np.random.randint(0, 11, size=(4, 4))

A_diag = np.diag(np.diag(A))
A_diag_1_upper = np.diag(np.diag(A, k=1), k=1) #  k is Diagonal in question. The default is 0. Use k>0 for diagonals above the main diagonal, and k<0 for diagonals below the main diagonal.


print(A_diag)
print(A_diag_1_upper)


[[5 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 2]]
[[0 2 0 0]
 [0 0 1 0]
 [0 0 0 7]
 [0 0 0 0]]


In [43]:
upper_bidiag = A_diag + A_diag_1_upper
upper_bidiag

array([[5, 2, 0, 0],
       [0, 2, 1, 0],
       [0, 0, 1, 7],
       [0, 0, 0, 2]])

### householder 하우스홀더 행렬

$
H = I - 2vv^{T}
$

정규화된 정의로는 $H = I - 2\frac{vv^{T}}{v^{T}v}$


- $H$는 대칭인 정사각 행렬이고 직교 행렬임. symmetric 하면서도 orthogonal 함.
    - 대칭(symmetric) 이므로 $H = H^{T}$
        - $H$는 대칭 행렬인 $I$ 에서 대칭 행렬 $2vv^{T}$을 뺀 것이므로 $H$도 대칭행렬임  
        - 왜 $2vv^{T}$ 가 대칭 행렬인가? => $vv^{T}$ 는 그 정의상 외적곱(outer product)이고, 같은 벡터를 외적곱을 하면 항상 대칭 행렬이 나온다.
    - 직교한다는 것은 $H^T = H^{-1}$ 이므로 $H^{T}H = HH^{T} = I$

- 어디에 쓰나?
    - 하우스홀더 행렬은 주로 행렬의 특정 열이나 행을 단순화하는 데 사용됩니다. 
    - 특정 벡터를 원하는 형태로 반사(reflection)시키는 데 사용됩니다. 이러한 반사를 이용해, 예를 들어 QR 분해나 고유값 문제에서 행렬을 단순화하는 데 사용됩니다. 하우스홀더 변환은 고유값 분해, 특이값 분해(SVD) 등의 계산을 더 효율적으로 만들 수 있습니다.


In [51]:
v = np.array([1, 0, 2, 3])
vvt = np.outer(v, v)
vtv = np.inner(v, v)

vvt, vtv

(array([[1, 0, 2, 3],
        [0, 0, 0, 0],
        [2, 0, 4, 6],
        [3, 0, 6, 9]]),
 14)

In [49]:
I = np.identity(len(v))
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [53]:
H = I - (2 * vvt / vtv)
H

array([[ 0.85714286,  0.        , -0.28571429, -0.42857143],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [-0.28571429,  0.        ,  0.42857143, -0.85714286],
       [-0.42857143,  0.        , -0.85714286, -0.28571429]])