### 대각화

$
A = PDP^{-1} \\ 
A^{n} = PD^{n}P^{-1}
$  

- P는 행렬 A의 고유벡터로 구성된 행렬입니다.
- D는 대각 행렬로, 그 대각선 위의 원소들이 A의 고유값입니다.
- 살펴보면 대각화도 결국 QR 분해 같이 행렬을 분해하는 방법론. 고윳값과 고유벡터의 개념을 사용한 것일 뿐.  
    - 행렬 분해의 예시로, LU 분해, QR 분해, 대각화, SVD, Cholesky 분해 등이 존재함.  


- 대각화는 보통 n * n 정사각 행렬에 대해서 행하는 행렬 분해방법입니다.
    - n * n 크기의 행렬 A가 대각화 가능하다? = A는 n개의 고유값을 가져야

### 직교 대각화

$A = PDP^{-1} = PDP^{T}$

- A가 대칭 행렬일 때($A = A^T$) 적용할 수 있습니다.
- A는 n개의 정규 직교 벡터로 이루어진 행렬이어야 합니다.  

### 고유값 분해 (eigen decomposition)

대각화와 표현이 동일함. 둘을 구별하는 실익이 없다... 

In [ ]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [2, 4, 5],
    [3, 5, 3],
])

E, V = np.linalg.eig(A)
E, V

(array([ 9.90754321,  0.05152112, -1.95906434]),
 array([[-0.36762518, -0.82102902, -0.43676432],
        [-0.67017224,  0.55950483, -0.48767152],
        [-0.64476422, -0.11342699,  0.75591892]]))

### SVD

- SVD는 정사각 행렬에만 사용하던 고윳값 분해를 m * n 직사각 행렬에서도 적용 가능하게 일반화한 것  
    - 차원 축소에 주로 사용됨

$𝐴 =𝑈Σ𝑉^{𝑇}$ 

- U와 V는 각각 왼쪽, 오른쪽 특이벡터 행렬이며, 이들은 각각 A와 A^{T}의 고유벡터를 열로 가지는 직교(orthogonal) 행렬입니다.
- Σ는 대각 행렬로, 행렬 A의 특이값(singular values)을 대각선 상에 가집니다. 이 특이값들은  A의 고유값의 제곱근에 해당합니다.

In [3]:
import numpy as np

B = np.array([
    [3, 6],
    [2, 3],
    [1, 2],
    [5, 5]
])

U, S, Vt = np.linalg.svd(B)

U, S, Vt

(array([[-0.6305882 ,  0.65070051, -0.34404196,  0.24613512],
        [-0.34294608,  0.0720764 ,  0.09856768, -0.93138466],
        [-0.21019607,  0.21690017,  0.9335582 ,  0.19297931],
        [-0.66375005, -0.72411888, -0.01971354,  0.18627693]]),
 array([10.50804076,  1.6065738 ]),
 array([[-0.58113622, -0.8138063 ],
        [-0.8138063 ,  0.58113622]]))

### LU 분해

- LU 분해는 주어진  n×n 정사각 행렬 A를 두 개의 행렬, 하삼각 행렬 L과 상삼각 행렬 U의 곱으로 표현하는 과정입니다:

In [4]:
from scipy.linalg import lu

A = np.array([
    [2, -2, -2],
    [0, -2, 2],
    [-1, 5, -2],
])

P, L, U = lu(A)

"""
L이 하삼각, U가 상삼각
P는 순열 행렬(Permutation matrix)입니다
기본적으로 단위 행렬(identity matrix)에 특정 행들이 교환된 형태

PA = LU 가 성립함.
"""
P, L, U

(array([[1., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.]]),
 array([[ 1. ,  0. ,  0. ],
        [-0.5,  1. ,  0. ],
        [ 0. , -0.5,  1. ]]),
 array([[ 2. , -2. , -2. ],
        [ 0. ,  4. , -3. ],
        [ 0. ,  0. ,  0.5]]))

In [7]:
np.allclose(np.matmul(P, A), np.matmul(L, U))

True