### 외적(outer product)

- outer product = 텐서 곱 (tensor product) 


$$
\mathbf{u} \otimes \mathbf{v} = \mathbf{u}\mathbf{v}^T = 
\begin{pmatrix}
u_1 \\
u_2 \\
u_3 
\end{pmatrix}

\begin{pmatrix}
v_1 & v_2 & v_3 & v_4
\end{pmatrix}

=
\begin{pmatrix}
u_1v_1 & u_1v_2 & u_1v_3 & u_1v_4 \\
u_2v_1 & u_2v_2 & u_2v_3 & u_2v_4 \\
u_3v_1 & u_3v_2 & u_3v_3 & u_3v_4
\end{pmatrix}

$$

In [2]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([-1, 0, 2])

np.outer(A, B)

array([[-1,  0,  2],
       [-2,  0,  4],
       [-3,  0,  6]])

### 크로네커 곱(Kronecker product)

-   A가 m×n 행렬이고 B가 p×q 행렬일 때, A와 B의 크로네커 곱 A⊗B는 mp×nq 행렬이 됩니다.

$$
\begin{bmatrix}
a_{11}B & a_{12}B & \cdots & a_{1n}B \\
a_{21}B & a_{22}B & \cdots & a_{2n}B \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1}B & a_{m2}B & \cdots & a_{mn}B
\end{bmatrix}
$$

In [3]:
import numpy as np

# 행렬 A 정의
A = np.array([[1, 2], [3, 4]])

# 행렬 B 정의
B = np.array([[0, 5], [6, 7]])

# 크로네커 곱 계산
C = np.kron(A, B)

print("행렬 A:")
print(A)
print("\n행렬 B:")
print(B)
print("\n크로네커 곱 A ⊗ B:")
print(C)


행렬 A:
[[1 2]
 [3 4]]

행렬 B:
[[0 5]
 [6 7]]

크로네커 곱 A ⊗ B:
[[ 0  5  0 10]
 [ 6  7 12 14]
 [ 0 15  0 20]
 [18 21 24 28]]


### 백터 곱 (vector product, cross product)

- 두 벡터에 모두 수직인 새로운 벡터를 생성합니다.

두 벡터 $(\mathbf{a} = (a_1, a_2, a_3))와 (\mathbf{b} = (b_1, b_2, b_3))$에 대해,  
이들의 크로스 프로덕트 $(\mathbf{a} \times \mathbf{b})$는 다음과 같이 계산됩니다:  

$
\mathbf{a} \times \mathbf{b} = \begin{vmatrix}
\mathbf{i} & \mathbf{j} & \mathbf{k} \\
a_1 & a_2 & a_3 \\
b_1 & b_2 & b_3
\end{vmatrix}
$

이 행렬식을 계산하면 다음과 같은 벡터를 얻습니다:

$
\mathbf{a} \times \mathbf{b} = (a_2b_3 - a_3b_2, a_3b_1 - a_1b_3, a_1b_2 - a_2b_1)
$

이 연산의 결과인 벡터는 원래의 두 벡터 $(\mathbf{a})$와 $(\mathbf{b})$ 모두에 수직입니다.  
크로스 프로덕트의 크기(또는 길이)는 $(\mathbf{a})$와 $(\mathbf{b})$가 이루는 평행사변형의 넓이와 같으며,   
이는 $(\|\mathbf{a}\| \|\mathbf{b}\| \sin \theta)$로 계산할 수 있습니다, 여기서 $(\theta)$는 두 벡터 사이의 각입니다.


In [7]:
import numpy as np

# 벡터 a와 b 정의
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 벡터 a와 b의 크로스 프로덕트 계산
cross_product = np.cross(a, b)

# 결과 출력
print("벡터 a:", a)
print("벡터 b:", b)
print("크로스 프로덕트 (벡터 a x 벡터 b):", cross_product)

# a, b에 대해서 수직일것이므로 내적하면 0일 것이다
np.allclose(np.inner(cross_product, a), 0), np.allclose(np.inner(cross_product, b), 0)


벡터 a: [1 2 3]
벡터 b: [4 5 6]
크로스 프로덕트 (벡터 a x 벡터 b): [-3  6 -3]


(True, True)

### 삼중곱 (triple product)  

- `스칼라 3중 곱`과 `벡터 3중 곱`으로 나뉨
- `스칼라 3중 곱`
    - $u \cdot (v \times w)$
    - v와 w를 벡터곱하고 u와 내적함
- `벡터 3중 곱`
    - $u \times (v \times w)$